/**
 * Extract numeric timestamp from an ID.
 * IDs generated by createLocalId / generateId look like "001742672072000-abc123".
 * For IDs that don't match this pattern, return 0 so they sort to the bottom (oldest).
 */
function extractTimestamp(id: string): number {
  if (!id) return 0;
  const match = id.match(/^(\d{13,15})-/);
  if (match) {
    return parseInt(match[1], 10);
  }
  // Try plain numeric prefix (e.g. "1742672072000")
  const numMatch = id.match(/^(\d{13,})/);
  if (numMatch) {
    return parseInt(numMatch[1], 10);
  }
  return 0;
}

/**
 * Sort items so that the newest (highest timestamp) appear FIRST (index 0 → top of page)
 * and the oldest appear LAST (bottom of page, near the 2026 footer).
 */
export function sortByNewest<T extends { id: string }>(items: T[]): T[] {
  return [...items].sort((a, b) => extractTimestamp(b.id) - extractTimestamp(a.id));
}
